import json
import pytest


from datetime import date
from pathlib import Path


from click.testing import CliRunner

from fx_alfred.cli import cli


pytestmark = [pytest.mark.cli, pytest.mark.docs, pytest.mark.integration]


def test_index_handles_multiple_prefixes(tmp_path, monkeypatch):
    rules_dir = tmp_path / "rules"
    rules_dir.mkdir()
    (rules_dir / "ALF-2100-SOP-Something.md").write_text("# ALF doc")
    (rules_dir / "NRV-2200-SOP-Other.md").write_text("# NRV doc")
    monkeypatch.chdir(tmp_path)
    runner = CliRunner()
    result = runner.invoke(cli, ["index"], catch_exceptions=False)
    assert result.exit_code == 0
    alf_index = rules_dir / "ALF-0000-REF-Document-Index.md"
    nrv_index = rules_dir / "NRV-0000-REF-Document-Index.md"
    assert alf_index.exists()
    assert nrv_index.exists()
    assert "2100" in alf_index.read_text()
    assert "2200" in nrv_index.read_text()


def test_index_only_indexes_prj_layer(sample_project, monkeypatch):
    """Index command only indexes PRJ layer documents."""
    monkeypatch.chdir(sample_project)
    runner = CliRunner()
    result = runner.invoke(cli, ["index"], catch_exceptions=False)
    assert result.exit_code == 0
    # Check that index was created in rules/ for ALF prefix
    doc_indexes = list((sample_project / "rules").glob("*-0000-REF-*.md"))
    assert len(doc_indexes) == 1
    content = doc_indexes[0].read_text()
    assert "2201" in content
    assert "2202" in content


def test_index_empty_project(tmp_path, monkeypatch):
    """Index command handles empty project."""
    monkeypatch.chdir(tmp_path)
    runner = CliRunner()
    result = runner.invoke(cli, ["index"], catch_exceptions=False)
    assert result.exit_code == 0
    assert "No PRJ documents" in result.output


def test_index_with_root_option(tmp_path):
    rules_dir = tmp_path / "rules"
    rules_dir.mkdir()
    (rules_dir / "TST-2100-SOP-Something.md").write_text("# test")
    runner = CliRunner()
    result = runner.invoke(
        cli, ["--root", str(tmp_path), "index"], catch_exceptions=False
    )
    assert result.exit_code == 0
    assert (rules_dir / "TST-0000-REF-Document-Index.md").exists()


def test_index_with_root_after_subcommand(tmp_path):
    rules_dir = tmp_path / "rules"
    rules_dir.mkdir()
    (rules_dir / "TST-2100-SOP-Something.md").write_text("# test")
    runner = CliRunner()
    result = runner.invoke(
        cli, ["index", "--root", str(tmp_path)], catch_exceptions=False
    )
    assert result.exit_code == 0
    assert (rules_dir / "TST-0000-REF-Document-Index.md").exists()


# --- Part A: Document Format Contract compliance tests ---


def _get_index_content(tmp_path) -> str:
    """Helper: create a project with one doc, run index, return index content."""
    rules_dir = tmp_path / "rules"
    rules_dir.mkdir(exist_ok=True)
    (rules_dir / "TST-2100-SOP-Something.md").write_text("# test")
    runner = CliRunner()
    runner.invoke(cli, ["index", "--root", str(tmp_path)], catch_exceptions=False)
    return (rules_dir / "TST-0000-REF-Document-Index.md").read_text()


def test_index_h1_format(tmp_path):
    """Generated index has compliant H1: # REF-0000: Document Index."""
    content = _get_index_content(tmp_path)
    assert content.startswith("# REF-0000: Document Index\n")


def test_index_has_applies_to(tmp_path):
    """Generated index has **Applies to:** field with correct prefix."""
    content = _get_index_content(tmp_path)
    assert "**Applies to:** TST project" in content


def test_index_has_last_updated(tmp_path):
    """Generated index has **Last updated:** field with today's date."""
    content = _get_index_content(tmp_path)
    today = date.today().isoformat()
    assert f"**Last updated:** {today}" in content


def test_index_has_last_reviewed(tmp_path):
    """Generated index has **Last reviewed:** field with today's date."""
    content = _get_index_content(tmp_path)
    today = date.today().isoformat()
    assert f"**Last reviewed:** {today}" in content


def test_index_has_status_active(tmp_path):
    """Generated index has **Status:** Active."""
    content = _get_index_content(tmp_path)
    assert "**Status:** Active" in content


def test_index_has_change_history(tmp_path):
    """Generated index has ## Change History section with table."""
    content = _get_index_content(tmp_path)
    assert "## Change History" in content
    assert "| Date | Change | By |" in content
    assert "Auto-generated by af index" in content


def test_index_has_separator_before_table(tmp_path):
    """Generated index has --- separator between metadata and body."""
    content = _get_index_content(tmp_path)
    lines = content.split("\n")
    # There should be a --- after metadata, before the table
    sep_indices = [i for i, line in enumerate(lines) if line.strip() == "---"]
    assert len(sep_indices) >= 1, "Expected at least one --- separator"


def test_index_passes_validate(tmp_path):
    """Generated index passes af validate (no issues for the index doc)."""
    _get_index_content(tmp_path)
    runner = CliRunner()
    result = runner.invoke(
        cli, ["validate", "--root", str(tmp_path)], catch_exceptions=False
    )
    # Index docs (ACID=0000) should not produce any issues
    assert "TST-0000" not in result.output or "0 issues" in result.output


def test_index_multiple_prefixes_compliant(tmp_path):
    """Generated indexes for multiple prefixes are all compliant."""
    rules_dir = tmp_path / "rules"
    rules_dir.mkdir()
    (rules_dir / "ALF-2100-SOP-Something.md").write_text("# ALF doc")
    (rules_dir / "NRV-2200-SOP-Other.md").write_text("# NRV doc")
    runner = CliRunner()
    runner.invoke(cli, ["index", "--root", str(tmp_path)], catch_exceptions=False)
    alf_content = (rules_dir / "ALF-0000-REF-Document-Index.md").read_text()
    nrv_content = (rules_dir / "NRV-0000-REF-Document-Index.md").read_text()
    assert "**Applies to:** ALF project" in alf_content
    assert "**Applies to:** NRV project" in nrv_content
    assert alf_content.startswith("# REF-0000: Document Index\n")
    assert nrv_content.startswith("# REF-0000: Document Index\n")


# --- Part B: Status column tests ---


def _make_doc_with_status(
    rules_dir: Path, acid: str, type_code: str, status: str
) -> Path:
    """Create a document with proper metadata including *Status:* field."""
    path = rules_dir / f"TST-{acid}-{type_code}-Doc-{acid}.md"
    path.write_text(
        f"# {type_code}-{acid}: Doc {acid}\n"
        f"\n"
        f"**Applies to:** TST project\n"
        f"**Last updated:** 2026-06-14\n"
        f"**Last reviewed:** 2026-06-14\n"
        f"**Status:** {status}\n"
        f"\n"
        f"---\n"
        f"\n"
        f"Body text.\n"
    )
    return path


def test_index_has_status_column_header(tmp_path):
    """Generated index table has a dedicated Status column."""
    rules_dir = tmp_path / "rules"
    rules_dir.mkdir()
    _make_doc_with_status(rules_dir, "2100", "SOP", "Active")
    runner = CliRunner()
    runner.invoke(cli, ["index", "--root", str(tmp_path)], catch_exceptions=False)
    content = (rules_dir / "TST-0000-REF-Document-Index.md").read_text()
    assert "| ACID | Type | Title | Status |" in content


def test_index_shows_active_in_status_column(tmp_path):
    """Active status is rendered in the Status column, not hidden."""
    rules_dir = tmp_path / "rules"
    rules_dir.mkdir()
    _make_doc_with_status(rules_dir, "2100", "SOP", "Active")
    runner = CliRunner()
    runner.invoke(cli, ["index", "--root", str(tmp_path)], catch_exceptions=False)
    content = (rules_dir / "TST-0000-REF-Document-Index.md").read_text()
    assert "| 2100 | SOP | Doc 2100 | Active |" in content


def test_index_renders_em_dash_when_status_missing(tmp_path):
    """A doc with no Status field renders an em dash in the Status column."""
    rules_dir = tmp_path / "rules"
    rules_dir.mkdir()
    (rules_dir / "TST-2100-SOP-Doc-2100.md").write_text("# SOP-2100: Doc 2100\n")
    runner = CliRunner()
    runner.invoke(cli, ["index", "--root", str(tmp_path)], catch_exceptions=False)
    content = (rules_dir / "TST-0000-REF-Document-Index.md").read_text()
    assert "| 2100 | SOP | Doc 2100 | — |" in content


@pytest.mark.parametrize(
    ("type_code", "status"),
    [
        ("SOP", "Active"),
        ("SOP", "Draft"),
        ("SOP", "Deprecated"),
        ("PRP", "Draft"),
        ("PRP", "Approved"),
        ("PRP", "Rejected"),
        ("PRP", "Implemented"),
        ("CHG", "Proposed"),
        ("CHG", "Approved"),
        ("CHG", "In Progress"),
        ("CHG", "Completed"),
        ("CHG", "Rolled Back"),
        ("ADR", "Proposed"),
        ("ADR", "Accepted"),
        ("ADR", "Superseded"),
        ("ADR", "Deprecated"),
        ("REF", "Active"),
        ("REF", "Draft"),
        ("REF", "Deprecated"),
        ("PLN", "Draft"),
        ("PLN", "Completed"),
        ("PLN", "Cancelled"),
        ("INC", "Open"),
        ("INC", "Resolved"),
        ("INC", "Monitoring"),
    ],
)
def test_index_shows_status_in_column(tmp_path, type_code, status):
    """Every allowed status is rendered verbatim in the Status column."""
    rules_dir = tmp_path / "rules"
    rules_dir.mkdir()
    _make_doc_with_status(rules_dir, "2100", type_code, status)
    runner = CliRunner()
    runner.invoke(cli, ["index", "--root", str(tmp_path)], catch_exceptions=False)
    content = (rules_dir / "TST-0000-REF-Document-Index.md").read_text()
    assert f"| 2100 | {type_code} | Doc 2100 | {status} |" in content


def test_index_handles_mixed_statuses(tmp_path):
    """Multiple docs with different statuses each show their own column value."""
    rules_dir = tmp_path / "rules"
    rules_dir.mkdir()
    _make_doc_with_status(rules_dir, "2100", "SOP", "Active")
    _make_doc_with_status(rules_dir, "2101", "PRP", "Rejected")
    _make_doc_with_status(rules_dir, "2102", "SOP", "Draft")
    _make_doc_with_status(rules_dir, "2103", "SOP", "Deprecated")
    runner = CliRunner()
    runner.invoke(cli, ["index", "--root", str(tmp_path)], catch_exceptions=False)
    content = (rules_dir / "TST-0000-REF-Document-Index.md").read_text()
    assert "| 2100 | SOP | Doc 2100 | Active |" in content
    assert "| 2101 | PRP | Doc 2101 | Rejected |" in content
    assert "| 2102 | SOP | Doc 2102 | Draft |" in content
    assert "| 2103 | SOP | Doc 2103 | Deprecated |" in content


# ── FXA-2314: index inherits projects.json redirect via scan_documents ────────


def test_index_mapped_context_includes_subproject_docs(tmp_path):
    """af index in a mapped context indexes the subproject (PRJ) docs, not local rules/."""
    alfred = Path.home() / ".alfred"
    alfred.mkdir(parents=True, exist_ok=True)

    ext_repo = tmp_path / "ext_repo"
    ext_repo.mkdir()

    nrv_dir = alfred / "NRV"
    nrv_dir.mkdir(exist_ok=True)
    (nrv_dir / "NRV-2500-SOP-Workflow-Routing-PRJ.md").write_text(
        "# SOP-2500: Workflow Routing PRJ\n"
        "\n"
        "**Applies to:** NRV\n"
        "**Status:** Active\n"
        "\n"
        "---\n"
        "\n"
        "NRV routing content.\n"
    )

    (alfred / "projects.json").write_text(
        json.dumps({"projects": {str(ext_repo.resolve()): "NRV"}}),
        encoding="utf-8",
    )

    runner = CliRunner()
    result = runner.invoke(
        cli, ["index", "--root", str(ext_repo)], catch_exceptions=False
    )
    assert result.exit_code == 0, result.output
    # index_cmd writes to ~/.alfred/<NAME>/ for a mapped root (write path is
    # symmetric with the read redirect); the subproject docs are indexed there.
    index_file = Path.home() / ".alfred" / "NRV" / "NRV-0000-REF-Document-Index.md"
    assert index_file.exists(), (
        "af index must generate an NRV prefix index that includes the subproject docs"
    )
    content = index_file.read_text()
    assert "2500" in content, "NRV-2500 must appear in the generated index"


# ── FXA-2314: index write-path redirect for mapped context (fix) ──────────────


def test_index_mapped_root_writes_index_to_subdir(tmp_path):
    """In a mapped context, af index writes the index to ~/.alfred/<NAME>/, not <repo>/rules/.

    Expected behavior after the fix: when --root points to a repo registered in
    projects.json, the generated index file is written into ~/.alfred/<NAME>/ so
    that reads and writes are symmetric.
    """
    alfred = Path.home() / ".alfred"
    alfred.mkdir(parents=True, exist_ok=True)

    ext_repo = tmp_path / "ext_repo"
    ext_repo.mkdir()

    nrv_dir = alfred / "NRV"
    nrv_dir.mkdir()
    # Two NRV-prefixed docs so there is a PRJ layer to index
    (nrv_dir / "NRV-2100-SOP-First-Doc.md").write_text(
        "# SOP-2100: First Doc\n"
        "\n"
        "**Applies to:** NRV\n"
        "**Status:** Active\n"
        "\n"
        "---\n"
        "\n"
        "NRV first-doc content.\n",
        encoding="utf-8",
    )
    (nrv_dir / "NRV-2101-REF-Second-Doc.md").write_text(
        "# REF-2101: Second Doc\n"
        "\n"
        "**Applies to:** NRV\n"
        "**Status:** Active\n"
        "\n"
        "---\n"
        "\n"
        "NRV second-doc content.\n",
        encoding="utf-8",
    )

    (alfred / "projects.json").write_text(
        json.dumps({"projects": {str(ext_repo.resolve()): "NRV"}}),
        encoding="utf-8",
    )

    runner = CliRunner()
    result = runner.invoke(
        cli,
        ["index", "--root", str(ext_repo)],
        catch_exceptions=False,
    )
    assert result.exit_code == 0, result.output
    # Index must land in ~/.alfred/NRV/, not in <repo>/rules/
    expected = nrv_dir / "NRV-0000-REF-Document-Index.md"
    assert expected.exists(), (
        f"Expected index at {expected} (in ~/.alfred/NRV/), "
        f"but it was not created there. Output: {result.output}"
    )
    # <repo>/rules/ must NOT be created at all
    assert not (ext_repo / "rules").exists(), (
        "<repo>/rules/ must not be created when root is a mapped context"
    )
    content = expected.read_text()
    assert "2100" in content
    assert "2101" in content


def test_index_unmapped_root_still_writes_to_rules(tmp_path):
    """Regression guard: an unmapped root still writes the index to <root>/rules/."""
    alfred = Path.home() / ".alfred"
    alfred.mkdir(parents=True, exist_ok=True)
    # No projects.json — this root is not mapped

    ext_repo = tmp_path / "ext_repo"
    ext_repo.mkdir()
    rules_dir = ext_repo / "rules"
    rules_dir.mkdir()
    (rules_dir / "TST-2100-SOP-Something.md").write_text(
        "# SOP-2100: Something\n"
        "\n"
        "**Applies to:** TST\n"
        "**Status:** Active\n"
        "\n"
        "---\n"
        "\n"
        "Content.\n",
        encoding="utf-8",
    )

    runner = CliRunner()
    result = runner.invoke(
        cli,
        ["index", "--root", str(ext_repo)],
        catch_exceptions=False,
    )
    assert result.exit_code == 0, result.output
    assert (rules_dir / "TST-0000-REF-Document-Index.md").exists()
